name: Test Docker Hub Secrets

# This is a TEST workflow to verify Docker Hub secrets are configured correctly
# It will NOT build or deploy anything - just test authentication

on:
  workflow_dispatch:  # Manual trigger only (won't run automatically)

jobs:
  test-secrets:
    name: Test Docker Hub Authentication
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code (not really needed, but good practice)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Test Docker Hub login with secrets
      - name: Test Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Verify login worked by pulling a test image
      - name: Verify Docker Hub Access
        run: |
          echo "✅ Docker Hub login successful!"
          echo "Testing pull access..."
          docker pull hello-world:latest
          echo "✅ Pull access confirmed!"

      # Step 4: Test tagging (doesn't push, just tags locally)
      - name: Test Image Tagging
        run: |
          echo "Testing image tagging..."
          docker tag hello-world:latest ${{ secrets.DOCKER_USERNAME }}/test-github-actions:latest
          echo "✅ Image tagging successful!"
          echo "Image: ${{ secrets.DOCKER_USERNAME }}/test-github-actions:latest"

      # Step 5: Display summary
      - name: Test Summary
        run: |
          echo "================================"
          echo "GitHub Secrets Test: ✅ PASSED"
          echo "================================"
          echo ""
          echo "Verified:"
          echo "  ✅ DOCKER_USERNAME secret exists"
          echo "  ✅ DOCKER_PASSWORD secret exists"
          echo "  ✅ Docker Hub authentication successful"
          echo "  ✅ Pull permissions confirmed"
          echo "  ✅ Image tagging works"
          echo ""
          echo "NOTE: This test did NOT push any images to Docker Hub"
          echo "      It only verified that secrets are configured correctly"
          echo ""
          echo "Next step: Ready for real Docker builds when approved!"
